filebeat.inputs:
  - type: log
    paths:
      - /var/log/*.log
    fields:
      app: django
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5000"]

setup.kibana:
  host: "kibana:5601"
